import {
  Baby,
  BadgePercent,
  BedDouble,
  Building2,
  Camera,
  Car,
  ClipboardList,
  CloudSun,
  Crown,
  Hotel,
  Landmark,
  MapPinned,
  Mic,
  Mountain,
  Palmtree,
  PartyPopper,
  Route,
  Scale,
  ShieldCheck,
  Stamp,
  Swords,
  Tag,
  Tent,
  Ticket,
  TrainFront,
  Wallet,
  Waves,
  MessagesSquare,
  Radar,
  CandlestickChart,
  CircuitBoard,
  Filter,
  BarChart3,
  Banknote,
  CloudCog,
  Bot,
  Cpu,
  HeartPulse,
  Zap,
  Cloud,
  BrainCircuit,
  ShoppingCart,
  Gamepad2,
  Link2,
  PlayCircle,
  Truck,
  UtensilsCrossed,
  Sparkles,
  Home,
  GraduationCap,
  Shirt,
  Wheat,
  Plane,
  Umbrella,
  Recycle,
  Rocket,
  Smartphone,
  Network,
  Globe,
  ListChecks,
  MessageCircle,
  Activity,
  Star,
  Lightbulb,
  UserSearch,
  FileBarChart,
  LineChart,
  FolderTree,
  type LucideIcon,
} from 'lucide-react'

const map: Record<string, LucideIcon> = {
  crown: Crown,
  scale: Scale,
  'shield-check': ShieldCheck,
  chess: Swords,
  tag: Tag,
  'chat-user': MessagesSquare,
  radar: Radar,
  candlestick: CandlestickChart,
  circuit: CircuitBoard,
  funnel: Filter,
  'bar-chart': BarChart3,
  'shield-scale': Banknote,
  'cloud-code': CloudCog,
  robot: Bot,
  chip: Cpu,
  'medical-cross': HeartPulse,
  'ev-bolt': Zap,
  cloud: Cloud,
  'brain-chip': BrainCircuit,
  cart: ShoppingCart,
  gamepad: Gamepad2,
  chain: Link2,
  play: PlayCircle,
  truck: Truck,
  utensils: UtensilsCrossed,
  lipstick: Sparkles,
  house: Home,
  graduation: GraduationCap,
  shirt: Shirt,
  wheat: Wheat,
  'plane-pin': Plane,
  'umbrella-shield': Umbrella,
  'recycle-leaf': Recycle,
  rocket: Rocket,
  'phone-chip': Smartphone,
  network: Network,
  'globe-chat': Globe,
  checklist: ListChecks,
  'chat-bubble': MessageCircle,
  'mood-wave': Activity,
  stars: Star,
  'lightbulb-shield': Lightbulb,
  'user-search': UserSearch,
  'doc-chart': FileBarChart,
  'line-bar': LineChart,
  folder: FolderTree,
  mountain: Mountain,
  island: Palmtree,
  'city-walk': Building2,
  landmark: Landmark,
  car: Car,
  'train-front': TrainFront,
  bed: BedDouble,
  hotel: Hotel,
  stamp: Stamp,
  'cloud-sun': CloudSun,
  baby: Baby,
  camera: Camera,
  wallet: Wallet,
  ticket: Ticket,
  tent: Tent,
  waves: Waves,
  'party-popper': PartyPopper,
  'badge-percent': BadgePercent,
  'map-pinned': MapPinned,
  clipboard: ClipboardList,
  mic: Mic,
  route: Route,
}

export function DomainIcon({
  name,
  size = 16,
  className = '',
}: {
  name: string
  size?: number
  className?: string
}) {
  const Icon = map[name] ?? Sparkles
  return <Icon size={size} className={className} strokeWidth={1.8} />
}
